# docker-compose.yml

version: '3'
services:
  db:
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: odys_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ".:/src"
      - "pgdata:/var/lib/postgresql/data"
    network_mode: host
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    # Init system helps clean up background process.
    init: true
    ports:
      - "8080:8080"
    network_mode: host
    depends_on:
      - db    
    volumes:
      - ".:/src"
    environment:
      PGRST_DB_URI: "postgres://authenticator:passmordor@0.0.0.0:5432/odys_dev"
      PGRST_DB_SCHEMA: "api"
      PGRST_DB_ANON_ROLE: "anon"
      PGRST_MAX_ROWS: "1000"
      PGRST_SERVER_HOST: "0.0.0.0"
      PGRST_SERVER_PORT: "3001"    
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    network_mode: host
    # Keeps docker container alive
    stdin_open: true
    volumes:
      - ".:/src"
volumes:
  pgdata:
